<a href="https://colab.research.google.com/github/shobha-nosimpler/GenAI/blob/main/genAi_category_from_description.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Using gpt-3.5-turbo-16 to output laptop details from laptop description

# Use case 1 : Determine category of the laptop

# Here we reade laptop description file and classify based on description into different categories
- general
- business
- gamer
- programmer
- multimedia

input laptop_description
------------------

0	The Dell Inspiron is a versatile laptop that c...

1	The MSI GL65 is a high-performance laptop desi...

2	The HP EliteBook is a premium laptop designed ...

3	The Lenovo IdeaPad is a versatile laptop that ...

4	The ASUS ZenBook Pro is a high-end laptop that...

output
---------
laptop_description	Category

0	The Dell Inspiron is a versatile laptop that c...	general

1	The MSI GL65 is a high-performance laptop desi...	gamer

2	The HP EliteBook is a premium laptop designed ...	business

3	The Lenovo IdeaPad is a versatile laptop that ...	general

4	The ASUS ZenBook Pro is a high-end laptop that...	gamer

# Testing openai API key

In [90]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (1.35.10)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (2.8.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.4)
Requirement already satisfied: typing-extensions<5,>=4.7 in /usr/local/lib/python3.10/dist-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2024.6.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1.9.0->openai) (2.20.0)

In [91]:
import openai

In [ ]:
# pass secret key for authentication
api_key = input("Enter your API key: ")
openai.api_key = api_key

In [93]:
# Simple user request to test
messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Who won IPL 2020"}
    ]

# Make a chat completion API call using the GPT-3.5-turbo model
chat_response = openai.chat.completions.create(
  model="gpt-3.5-turbo-16k",
  messages=messages
)

# Print chat response as needed
chat_response

ChatCompletion(id='chatcmpl-9hanZFLlBZXQw6SvZ48bUpQ2mp4HK', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Mumbai Indians won the IPL 2020.', role='assistant', function_call=None, tool_calls=None))], created=1720176585, model='gpt-3.5-turbo-16k-0613', object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=10, prompt_tokens=23, total_tokens=33))

# Read the laptop descriptions csv file into a data frame

In [94]:
import pandas as pd
import numpy as np

In [95]:
# Read the CSV file into a pandas DataFrame
df = pd.read_csv('/content/laptop_descriptions.csv')

# Display the DataFrame
print(df.head())

                                  laptop_description
0  The Dell Inspiron is a versatile laptop that c...
1  The MSI GL65 is a high-performance laptop desi...
2  The HP EliteBook is a premium laptop designed ...
3  The Lenovo IdeaPad is a versatile laptop that ...
4  The ASUS ZenBook Pro is a high-end laptop that...

# Prompt clearly explaining the categories

In [49]:
mcq1_prompt = '''
From the description of a laptop (delimited by '###'), you have to identify what role does the laptop serve. Refer to the key value pairs of categories and category details below. Identify which of the following details does the product description fits best and assign that category to that latpop. \n
Categories:
[
    'general': 'For general purpose use such as light web browsing, editing documents etc.'
    'business': 'For business users, the focus is on portability, battery backup and general purpose use.'
    'gamer': 'For gamers, the focus is primarily on high-performance, high-end graphics requirement, efficient processor etc.'
    'programmer': 'For programmers, the focus is on performance, battery backup, high-end RAM etc.'
    'multimedia': 'For multimedia use cases, the requirements are a good quality/ high resolution display, wide screens, good audio and video quality, battery backup, efficiency etc.' # Write the prompt here
] \n
Laptop description: {description}
'''

In [50]:
# Best practice
import openai
from tenacity import retry, wait_random_exponential, stop_after_attempt

# Retry up to 6 times with exponential backoff, starting at 1 second and maxing out at 20 seconds delay
@retry(wait=wait_random_exponential(min=1, max=20), stop=stop_after_attempt(6))
def get_chat_response_mcq1(user_request):

  '''
  This function ONLY takes `user_request` as the input argument.
  As you can see, the System Prompt is given inside the function itself so we don't require to give it as an input argument
  '''

  MODEL = 'gpt-3.5-turbo-16k'# Define GPT model

  SYSTEM_MESSAGE = '''You are a shopping assistant. The user will give you laptop description and some categories and their details. You have to find out which of the categories does the laptop fit best according to description. Remember to only give one word output, the category name, from the list of categories only, which resembles most closely.''' # Default System Message

  try:

    messages = [

                {"role" : 'system', "content": SYSTEM_MESSAGE},
                {"role" : 'user', "content": user_request}
    ] # Define the list of messages

    response = openai.chat.completions.create(
        model = MODEL,
        messages = messages
    ) # Get the ChatCompletion Response from the GPT-3.5 model


    # Parse the response_content from the message
    response_content = response.choices[0].message.content

    return response_content

  # Raise exception
  except Exception as e:
    print(f"An error occured: {e}")
    return None

In [51]:
laptop_df = df.copy()
laptop_df.head()

                                  laptop_description
0  The Dell Inspiron is a versatile laptop that c...
1  The MSI GL65 is a high-performance laptop desi...
2  The HP EliteBook is a premium laptop designed ...
3  The Lenovo IdeaPad is a versatile laptop that ...
4  The ASUS ZenBook Pro is a high-end laptop that...

In [52]:
# creates a list of dictionaries from the dataframe
# the column name is the key, and row is the value
# each dictionary has the same key, which is the column name
#and value is the row value

laptop_dict = laptop_df.to_dict(orient='records')
type(laptop_dict)

list

In [53]:
len(laptop_dict)

20

In [12]:
laptop_dict

[{'laptop_description': 'The Dell Inspiron is a versatile laptop that combines powerful performance and affordability. It features an Intel Core i5 processor clocked at 2.4 GHz, ensuring smooth multitasking and efficient computing. With 8GB of RAM and an SSD, it offers quick data access and ample storage capacity. The laptop sports a vibrant 15.6" LCD display with a resolution of 1920x1080, delivering crisp visuals and immersive viewing experience. Weighing just 2.5 kg, it is highly portable, making it ideal for on-the-go usage. Additionally, it boasts an Intel UHD GPU for decent graphical performance and a backlit keyboard for enhanced typing convenience. With a one-year warranty and a battery life of up to 6 hours, the Dell Inspiron is a reliable companion for work or entertainment. All these features are packed at an affordable price of 35,000, making it an excellent choice for budget-conscious users.'},
 {'laptop_description': 'The MSI GL65 is a high-performance laptop designed for gaming enthusiasts. Powered by an Intel Core i7 processor running at 2.6 GHz, it delivers exceptional processing power for smooth gaming and demanding tasks. With 16GB of RAM and a combination of HDD and SSD storage, it offers ample memory and fast data access. The laptop features a 15.6" IPS display with a resolution of 1920x1080, ensuring vivid colors and wide viewing angles for an immersive gaming experience. Equipped with an NVIDIA GTX graphics card, it provides excellent visual performance and smooth gameplay. Weighing just 2.3 kg, it is a portable option for gamers on the move. The laptop also boasts an RGB keyboard, allowing customizable lighting effects for a personalized gaming setup. With a two-year warranty and a battery life of up to 4 hours, the MSI GL65 offers reliability and durability. Priced at 55,000, it offers excellent value for money for gamers seeking a powerful gaming laptop.'},
 {'laptop_description': 'The HP EliteBook is a premium laptop designed for professionals who value performance and security. It features an Intel Core i7 processor clocked at 2.8 GHz, providing exceptional speed and power for demanding tasks. With 16GB of RAM and an SSD, it offers fast and efficient multitasking and storage capabilities. The laptop sports a 14" LED display with a resolution of 1920x1080, delivering sharp visuals and vibrant colors. It also comes with an Intel UHD GPU for decent graphical performance. Weighing just 1.5 kg, it is lightweight and highly portable. The laptop is equipped with a fingerprint sensor for secure and convenient login. With a three-year warranty and a battery life of up to 8 hours, it ensures long-lasting reliability. Priced at 90,000, the HP EliteBook provides top-notch features and durability for professional users.'},
 {'laptop_description': 'The Lenovo IdeaPad is a versatile laptop that balances performance and affordability. It features an Intel Core i3 processor running at 2.1 GHz, offering reliable computing power for everyday tasks. With 8GB of RAM and an HDD, it provides adequate memory and storage capacity. The laptop sports a 15.6" TN display with a resolution of 1366x768, delivering decent visuals for multimedia consumption. It comes with an Intel UHD GPU for basic graphical performance. Weighing 2.2 kg, it is moderately portable. The laptop is equipped with Dolby Audio for immersive sound quality during media playback. With a one-year warranty and a battery life of up to 5 hours, the Lenovo IdeaPad ensures reliable performance. Priced at 25,000, it offers affordability for users on a budget.'},
 {'laptop_description': 'The ASUS ZenBook Pro is a high-end laptop that offers exceptional performance and a stunning display. It is powered by an Intel Core i9 processor clocked at 3.1 GHz, providing outstanding processing power for demanding tasks and gaming. With a massive 64GB of RAM and an SSD, it offers extensive memory and storage capabilities for multitasking and data-intensive applications. The laptop features a 15.6" OLED display with a resolution of 3840x2160, delivering incredibly sharp visuals and vibrant colors. Equipped with an NVIDIA RTX graphics card, it offers top-notch graphical performance for gaming and content creation. Weighing just 1.8 kg, it is highly portable. The laptop features a NanoEdge display with thin bezels for an immersive viewing experience. With a two-year warranty and a battery life of up to 7 hours, the ASUS ZenBook Pro combines reliability and durability. Priced at 200,000, it caters to users seeking uncompromising performance and a premium display.'},
 {'laptop_description': 'The Acer Predator is a powerhouse laptop designed for gaming enthusiasts. It is equipped with an Intel Core i7 processor clocked at 2.8 GHz, providing exceptional processing power for seamless gaming and demanding tasks. With 16GB of RAM and an SSD, it offers fast and efficient multitasking and storage capabilities. The laptop features a large 17.3" IPS display with a resolution of 1920x1080, delivering stunning visuals and wide viewing angles. It also comes with an NVIDIA GTX graphics card for impressive gaming performance. Weighing 3.2 kg, it is a bit on the heavier side but still offers portability. The laptop features dual cooling fans for effective heat dissipation during intense gaming sessions. With a one-year warranty and a battery life of up to 5 hours, the Acer Predator ensures reliability and endurance. Priced at 80,000, it provides excellent value for gamers seeking powerful gaming performance.'},
 {'laptop_description': 'The Microsoft Surface Laptop is a premium device that combines sleek design with excellent performance. It is powered by an Intel Core i5 processor running at 1.6 GHz, providing efficient computing power for productivity and multimedia tasks. With 8GB of RAM and an SSD, it offers fast and reliable performance along with ample storage capacity. The laptop features a 13.5" PixelSense touchscreen display with a resolution of 2256x1504, delivering vibrant visuals and precise touch input. It comes with Intel Iris Plus integrated graphics for smooth graphics performance. Weighing just 1.3 kg, it is highly portable and suitable for on-the-go usage. The laptop features a touchscreen display, adding versatility to interaction and creativity. With a one-year warranty and an impressive battery life of up to 10 hours, the Microsoft Surface Laptop ensures reliability and all-day productivity. Priced at 90,000, it offers a premium experience for users seeking a stylish and high-performance laptop.'},
 {'laptop_description': 'The Lenovo ThinkPad is a powerful laptop designed for professional users. It is equipped with a Ryzen 7 processor from AMD clocked at 3.0 GHz, providing strong processing capabilities for demanding tasks. With 16GB of RAM and an SSD, it offers smooth multitasking and fast storage access. The laptop features a 14" IPS display with a resolution of 2560x1440, delivering sharp visuals and accurate colors. It also comes with an NVIDIA GTX graphics card for enhanced graphical performance. Weighing just 1.6 kg, it is lightweight and highly portable. The laptop features a backlit keyboard for comfortable typing in low-light environments. With a three-year warranty and a battery life of up to 6 hours, the Lenovo ThinkPad offers reliability and durability. Priced at 60,000, it is an excellent choice for professionals seeking powerful performance and a versatile display.'},
 {'laptop_description': 'The HP Pavilion is a budget-friendly laptop that offers reliable performance for everyday computing tasks. It features an Intel Core i5 processor running at 2.3 GHz, providing decent processing power for productivity and entertainment. With 12GB of RAM and an HDD, it offers a balance between memory capacity and storage space. The laptop sports a 15.6" LCD display with a resolution of 1366x768, offering satisfactory visuals for everyday use. It comes with Intel UHD integrated graphics for basic graphical performance. Weighing 2.1 kg, it strikes a balance between portability and a larger display. The laptop features B&O audio for an enhanced audio experience during multimedia playback. With a one-year warranty and a battery life of up to 4 hours, the HP Pavilion ensures reliable performance for day-to-day tasks. Priced at 30,000, it provides affordability for budget-conscious users seeking'},
 {'laptop_description': 'The ASUS ROG Strix G is a high-performance gaming laptop designed for gamers seeking power and style. It is equipped with an Intel Core i7 processor clocked at 2.9 GHz, providing exceptional processing power for smooth gaming and demanding tasks. With 16GB of RAM and an SSD, it offers fast and efficient multitasking and storage capabilities. The laptop features a large 17.3" IPS display with a resolution of 1920x1080, delivering stunning visuals and wide viewing angles. It comes with an NVIDIA RTX graphics card for immersive gaming performance. Weighing 2.9 kg, it is slightly heavier but still offers portability. The laptop features an Aura Sync RGB keyboard, allowing customizable lighting effects for a personalized gaming setup. With a two-year warranty and a battery life of up to 5 hours, the ASUS ROG Strix G ensures reliability and endurance. Priced at 85,000, it offers excellent value for gamers seeking powerful gaming performance with stylish aesthetics.'},
 {'laptop_description': 'The Dell XPS 15 is a premium laptop that combines powerful performance with a stunning display. It is powered by an Intel Core i9 processor running at 2.8 GHz, offering exceptional processing power for demanding tasks and content creation. With 32GB of RAM and an SSD, it provides ample memory and fast storage access for multitasking and data-intensive applications. The laptop features a 15.6" OLED display with a resolution of 3840x2160, delivering incredibly sharp visuals and vibrant colors. Equipped with an NVIDIA GTX graphics card, it offers excellent graphical performance for gaming and content creation. Weighing just 1.8 kg, it is highly portable. The laptop features an Adobe RGB color gamut, ensuring accurate and vibrant color reproduction for creative professionals. With a three-year warranty and a battery life of up to 8 hours, the Dell XPS 15 combines reliability and durability. Priced at 180,000, it caters to users seeking uncompromising performance and a premium display.'},
 {'laptop_description': 'The Lenovo ThinkPad X1 Carbon is a sleek and lightweight laptop designed for professionals on the go. It is equipped with an Intel Core i7 processor running at 2.6 GHz, providing strong processing capabilities for multitasking and productivity. With 16GB of RAM and an SSD, it offers fast and efficient performance along with ample storage capacity. The laptop features a 14" IPS display with a resolution of 2560x1440, delivering sharp visuals and accurate colors. It comes with Intel UHD integrated graphics for decent graphical performance. Weighing just 1.13 kg, it is extremely lightweight and highly portable. The laptop features an IR camera for face unlock, providing convenient and secure login options. With a three-year warranty and an impressive battery life of up to 12 hours, the Lenovo ThinkPad X1 Carbon ensures reliability and long-lasting productivity. Priced at 130,000, it offers top-notch performance and portability for professionals.'},
 {'laptop_description': 'The Acer Swift 3 is a lightweight and affordable laptop that offers a balance of performance and portability. It features an AMD Ryzen 5 processor clocked at 2.3 GHz, providing reliable processing power for everyday tasks and multimedia consumption. With 8GB of RAM and an SSD, it offers smooth multitasking and fast storage access. The laptop features a 14" IPS display with a resolution of 1920x1080, delivering crisp visuals and wide viewing angles. It comes with an AMD Radeon integrated graphics card for decent graphical performance. Weighing just 1.2 kg, it is incredibly lightweight and highly portable. The laptop features a fingerprint reader for secure and convenient login options. With a one-year warranty and a battery life of up to 9 hours, the Acer Swift 3 ensures reliability and endurance for everyday use. Priced at 50,000, it offers affordability and portability for users seeking a reliable laptop for their daily computing needs.'},
 {'laptop_description': 'The Apple MacBook Air is a sleek and lightweight laptop that offers excellent performance and a seamless user experience. It is powered by the Apple M1 chip clocked at 3.2 GHz, providing powerful and efficient processing capabilities. With 16GB of RAM and an SSD, it offers fast and smooth multitasking along with ample storage space. The laptop features a 13.3" Retina display with a resolution of 2560x1600, delivering sharp and vibrant visuals. It is equipped with the Apple M1 integrated graphics, ensuring smooth graphics performance. Weighing just 1.29 kg, it is highly portable and suitable for on-the-go usage. The laptop features Touch ID, allowing secure and convenient login options. With a three-year warranty and an impressive battery life of up to 14 hours, the Apple MacBook Air ensures reliability and endurance. Priced at 100,000, it offers a premium experience for users seeking a powerful and lightweight laptop with seamless integration into the macOS ecosystem.'},
 {'laptop_description': 'The MSI Prestige 14 is a compact and stylish laptop designed for professionals and content creators. It features an Intel Core i5 processor running at 2.4 GHz, providing reliable performance for multitasking and creative work. With 16GB of RAM and an SSD, it offers fast and responsive performance along with ample storage capacity. The laptop features a 14" IPS display with a resolution of 1920x1080, delivering accurate colors and wide viewing angles. It comes with an NVIDIA GTX graphics card for enhanced graphical performance. Weighing just 1.29 kg, it is highly portable and suitable for on-the-go productivity. The laptop features True Color Technology, ensuring color accuracy for content creation. With a two-year warranty and a battery life of up to 8 hours, the MSI Prestige 14 offers reliability and endurance for professional use. Priced at 70,000, it provides a balance of performance, portability, and affordability.'},
 {'laptop_description': 'The ASUS ZenBook 13 is a lightweight and powerful laptop that offers a premium computing experience. It is equipped with an Intel Core i7 processor running at 2.8 GHz, providing strong processing power for multitasking and productivity. With 16GB of RAM and an SSD, it offers fast and responsive performance along with ample storage capacity. The laptop features a 13.3" NanoEdge display with a resolution of 1920x1080, delivering crisp visuals and immersive viewing. It comes with Intel Iris Xe integrated graphics for smooth graphics performance. Weighing just 1.11 kg, it is incredibly lightweight and highly portable. The laptop features military-grade durability, ensuring durability and reliability. With a two-year warranty and an impressive battery life of up to 11 hours, the ASUS ZenBook 13 offers long-lasting performance and endurance. Priced at 95,000, it provides a premium experience for users seeking a powerful and lightweight laptop.'},
 {'laptop_description': 'The Dell Precision 5550 is a high-performance laptop designed for professionals and creators who require powerful processing capabilities. It is equipped with an Intel Xeon processor running at 2.6 GHz, providing exceptional processing power for demanding tasks and content creation. With 32GB of RAM and an SSD, it offers seamless multitasking and ample storage capacity for large projects. The laptop features a 15.6" OLED display with a resolution of 3840x2160, delivering stunning visuals and accurate color reproduction. It is equipped with an NVIDIA Quadro graphics card, ensuring smooth graphics performance for professional applications. Weighing 1.83 kg, it is lightweight and portable, making it suitable for professionals on the go. The laptop features Thunderbolt 3 connectivity, providing fast data transfer and versatile connectivity options. With a three-year warranty and a battery life of up to 6 hours, the Dell Precision 5550 offers reliability and durability for demanding professional use. Priced at 250,000, it caters to professionals who require uncompromising performance and top-notch display quality.'},
 {'laptop_description': 'The HP ENVY x360 is a versatile 2-in-1 convertible laptop that combines performance and flexibility. It features an Intel Core i7 processor running at 2.8 GHz, providing powerful processing capabilities for multitasking and productivity. With 16GB of RAM and an SSD, it offers fast and efficient performance along with ample storage space. The laptop features a 15.6" IPS display with a resolution of 1920x1080, delivering vibrant visuals and wide viewing angles. It comes with Intel Iris Xe integrated graphics for smooth graphics performance. Weighing 2.05 kg, it offers a good balance between portability and functionality. The laptop features a convertible design, allowing you to switch between laptop and tablet modes for enhanced versatility. With a one-year warranty and a battery life of up to 7 hours, the HP ENVY x360 offers reliability and endurance for everyday use. Priced at 80,000, it provides a versatile computing experience at an affordable price point.'},
 {'laptop_description': 'The Razer Blade 15 is a high-performance gaming laptop that delivers exceptional power and visual excellence. It is powered by an Intel Core i7 processor running at 2.6 GHz, providing robust processing power for demanding gaming and content creation tasks. With 16GB of RAM and an SSD, it offers fast and responsive performance along with ample storage capacity. The laptop features a 15.6" IPS display with a resolution of 1920x1080, delivering vibrant visuals and immersive gaming experiences. It comes with an NVIDIA RTX graphics card for outstanding graphical performance. Weighing 2.09 kg, it strikes a balance between portability and power. The laptop features a Chroma RGB keyboard, allowing customizable lighting effects for a personalized gaming setup. With a one-year warranty and a battery life of up to 6 hours, the Razer Blade 15 ensures reliability and endurance for gaming enthusiasts. Priced at 150,000, it offers a premium gaming experience with powerful performance and eye-catching aesthetics.'},
 {'laptop_description': 'The Apple MacBook Pro is a high-end laptop that combines top-tier performance with a stunning display. It is equipped with an Intel Core i9 processor running at 2.9 GHz, providing exceptional processing power for demanding tasks and content creation. With 32GB of RAM and an SSD, it offers seamless multitasking and fast storage access for large projects. The laptop features a 16" Retina display with a resolution of 3072x1920, delivering breathtaking visuals and precise color reproduction. It comes with an AMD Radeon graphics card, ensuring smooth graphics performance for professional applications. Weighing 2.02 kg, it is relatively lightweight for its size. The laptop features a True Tone display, adjusting the color temperature to match the ambient lighting for a more natural viewing experience. With a three-year warranty and a battery life of up to 10 hours, the Apple MacBook Pro offers reliability and endurance for professionals. Priced at 280,000, it caters to users who require uncompromising performance and a superior display for their demanding workloads.'}]

In [54]:
# access the first description form the list of descriptions
laptop_dict[0]['laptop_description']

'The Dell Inspiron is a versatile laptop that combines powerful performance and affordability. It features an Intel Core i5 processor clocked at 2.4 GHz, ensuring smooth multitasking and efficient computing. With 8GB of RAM and an SSD, it offers quick data access and ample storage capacity. The laptop sports a vibrant 15.6" LCD display with a resolution of 1920x1080, delivering crisp visuals and immersive viewing experience. Weighing just 2.5 kg, it is highly portable, making it ideal for on-the-go usage. Additionally, it boasts an Intel UHD GPU for decent graphical performance and a backlit keyboard for enhanced typing convenience. With a one-year warranty and a battery life of up to 6 hours, the Dell Inspiron is a reliable companion for work or entertainment. All these features are packed at an affordable price of 35,000, making it an excellent choice for budget-conscious users.'

In [55]:
# append the description to the mcq1_promt which has categories defined
prompt = mcq1_prompt.format(description=laptop_dict[0]['laptop_description'])
prompt

'\nFrom the description of a laptop (delimited by \'###\'), you have to identify what role does the laptop serve. Refer to the key value pairs of categories and category details below. Identify which of the following details does the product description fits best and assign that category to that latpop. \n\nCategories:\n[\n    \'general\': \'For general purpose use such as light web browsing, editing documents etc.\'\n    \'business\': \'For business users, the focus is on portability, battery backup and general purpose use.\'\n    \'gamer\': \'For gamers, the focus is primarily on high-performance, high-end graphics requirement, efficient processor etc.\'\n    \'programmer\': \'For programmers, the focus is on performance, battery backup, high-end RAM etc.\'\n    \'multimedia\': \'For multimedia use cases, the requirements are a good quality/ high resolution display, wide screens, good audio and video quality, battery backup, efficiency etc.\' # Write the prompt here\n] \n\nLaptop description: The Dell Inspiron is a versatile laptop that combines powerful performance and affordability. It features an Intel Core i5 processor clocked at 2.4 GHz, ensuring smooth multitasking and efficient computing. With 8GB of RAM and an SSD, it offers quick data access and ample storage capacity. The laptop sports a vibrant 15.6" LCD display with a resolution of 1920x1080, delivering crisp visuals and immersive viewing experience. Weighing just 2.5 kg, it is highly portable, making it ideal for on-the-go usage. Additionally, it boasts an Intel UHD GPU for decent graphical performance and a backlit keyboard for enhanced typing convenience. With a one-year warranty and a battery life of up to 6 hours, the Dell Inspiron is a reliable companion for work or entertainment. All these features are packed at an affordable price of 35,000, making it an excellent choice for budget-conscious users.\n'

In [56]:
# assign the laptop category to the column laptop_category
#laptop_df.at[0,'Category'] = get_chat_response_mcq1(prompt)
get_chat_response_mcq1(prompt)

'multimedia'

In [59]:
# Define function to tag each laptop description with predefined category

def tag_laptop_description(df_laptop_desc, mcq1_prompt):
  # create a list of dictionaries with each row as value, and column name as key
  laptop_dict = df_laptop_desc.to_dict(orient='records')

  # For each record, that as the description create a prompt to get the category

  # Get the laptop category for each description

  for i in range(len(laptop_dict)):
    prompt = mcq1_prompt.format(description=laptop_dict[i]['laptop_description'])
    #laptop_dict[i]['Category'] = get_chat_response_mcq1(prompt)
    # Assign the laptop category to the column laptop_category
    laptop_category = get_chat_response_mcq1(prompt)
    df_laptop_desc.at[i,'Category'] = laptop_category

  return df_laptop_desc

In [60]:
tag_df = tag_laptop_description(df, mcq1_prompt)

In [15]:
print(df.head())

                                  laptop_description
0  The Dell Inspiron is a versatile laptop that c...
1  The MSI GL65 is a high-performance laptop desi...
2  The HP EliteBook is a premium laptop designed ...
3  The Lenovo IdeaPad is a versatile laptop that ...
4  The ASUS ZenBook Pro is a high-end laptop that...

In [61]:
print(tag_df.head())

                                  laptop_description    Category
0  The Dell Inspiron is a versatile laptop that c...     general
1  The MSI GL65 is a high-performance laptop desi...       gamer
2  The HP EliteBook is a premium laptop designed ...    business
3  The Lenovo IdeaPad is a versatile laptop that ...  multimedia
4  The ASUS ZenBook Pro is a high-end laptop that...       gamer

# Usecase 2: Extracting laptop properties from laptop description

# Instead of single output, get a json output with defined structure

In [17]:
structure = '''{
    "Brand": ___ ,
    "Model Name": ___ ,
    "GPU processor": ___ ,
    "Display Resolution": ___ ,
    "Weight": ___ ,
    "Processor": ___ ,
    "Clock speed": ___ ,
    "Budget": ___
}'''

In [18]:
mcq2_prompt = '''
Laptop Decription: {description}
From the laptop decription above, you have to extract relevant values for the following dictionary items. The dictionary structure should be as follows: {str}
Try giving quantitative, absolute, or numerical outputs. Try not to give qualitative or adjective outputs. for example: If the processing speed of a laptop is 2.4GHz, then, in the "processing speed" key, give output as '2.4GHz' instead of 'very fast'.
Extract only one word values of these properties. Fill in the blanks for each product and output each product's dictionary in json format.
'''

In [19]:
def get_chat_response_mcq2(user_request):

  MODEL = 'gpt-3.5-turbo-16k'# Define GPT model

  SYSTEM_MESSAGE = 'You are a helpful shopping assitant.'# Default System Message

  try:
  # Define the list of messages
    messages = [
        {'role': 'system', 'content': SYSTEM_MESSAGE},
        {'role': 'user', 'content': user_request}
    ]

# Get the ChatCompletion Response from the GPT-3.5 model
    response = openai.chat.completions.create(
        model = MODEL,
        messages = messages,
        #response_format = {'type': 'json_object'}
    )

    response_content = response.choices[0].message.content
    # Parse the response_content from the message

    return response_content

  # Raise exception error
  except Exception as e:
    print(f"An error occurred: {e}")
    return None

In [20]:
laptop_df.head()

                                  laptop_description    Category
0  The Dell Inspiron is a versatile laptop that c...  multimedia
1  The MSI GL65 is a high-performance laptop desi...       gamer
2  The HP EliteBook is a premium laptop designed ...    business
3  The Lenovo IdeaPad is a versatile laptop that ...  multimedia
4  The ASUS ZenBook Pro is a high-end laptop that...       gamer

In [44]:
laptop_dict

[{'laptop_description': 'The Dell Inspiron is a versatile laptop that combines powerful performance and affordability. It features an Intel Core i5 processor clocked at 2.4 GHz, ensuring smooth multitasking and efficient computing. With 8GB of RAM and an SSD, it offers quick data access and ample storage capacity. The laptop sports a vibrant 15.6" LCD display with a resolution of 1920x1080, delivering crisp visuals and immersive viewing experience. Weighing just 2.5 kg, it is highly portable, making it ideal for on-the-go usage. Additionally, it boasts an Intel UHD GPU for decent graphical performance and a backlit keyboard for enhanced typing convenience. With a one-year warranty and a battery life of up to 6 hours, the Dell Inspiron is a reliable companion for work or entertainment. All these features are packed at an affordable price of 35,000, making it an excellent choice for budget-conscious users.'},
 {'laptop_description': 'The MSI GL65 is a high-performance laptop designed for gaming enthusiasts. Powered by an Intel Core i7 processor running at 2.6 GHz, it delivers exceptional processing power for smooth gaming and demanding tasks. With 16GB of RAM and a combination of HDD and SSD storage, it offers ample memory and fast data access. The laptop features a 15.6" IPS display with a resolution of 1920x1080, ensuring vivid colors and wide viewing angles for an immersive gaming experience. Equipped with an NVIDIA GTX graphics card, it provides excellent visual performance and smooth gameplay. Weighing just 2.3 kg, it is a portable option for gamers on the move. The laptop also boasts an RGB keyboard, allowing customizable lighting effects for a personalized gaming setup. With a two-year warranty and a battery life of up to 4 hours, the MSI GL65 offers reliability and durability. Priced at 55,000, it offers excellent value for money for gamers seeking a powerful gaming laptop.'},
 {'laptop_description': 'The HP EliteBook is a premium laptop designed for professionals who value performance and security. It features an Intel Core i7 processor clocked at 2.8 GHz, providing exceptional speed and power for demanding tasks. With 16GB of RAM and an SSD, it offers fast and efficient multitasking and storage capabilities. The laptop sports a 14" LED display with a resolution of 1920x1080, delivering sharp visuals and vibrant colors. It also comes with an Intel UHD GPU for decent graphical performance. Weighing just 1.5 kg, it is lightweight and highly portable. The laptop is equipped with a fingerprint sensor for secure and convenient login. With a three-year warranty and a battery life of up to 8 hours, it ensures long-lasting reliability. Priced at 90,000, the HP EliteBook provides top-notch features and durability for professional users.'},
 {'laptop_description': 'The Lenovo IdeaPad is a versatile laptop that balances performance and affordability. It features an Intel Core i3 processor running at 2.1 GHz, offering reliable computing power for everyday tasks. With 8GB of RAM and an HDD, it provides adequate memory and storage capacity. The laptop sports a 15.6" TN display with a resolution of 1366x768, delivering decent visuals for multimedia consumption. It comes with an Intel UHD GPU for basic graphical performance. Weighing 2.2 kg, it is moderately portable. The laptop is equipped with Dolby Audio for immersive sound quality during media playback. With a one-year warranty and a battery life of up to 5 hours, the Lenovo IdeaPad ensures reliable performance. Priced at 25,000, it offers affordability for users on a budget.'},
 {'laptop_description': 'The ASUS ZenBook Pro is a high-end laptop that offers exceptional performance and a stunning display. It is powered by an Intel Core i9 processor clocked at 3.1 GHz, providing outstanding processing power for demanding tasks and gaming. With a massive 64GB of RAM and an SSD, it offers extensive memory and storage capabilities for multitasking and data-intensive applications. The laptop features a 15.6" OLED display with a resolution of 3840x2160, delivering incredibly sharp visuals and vibrant colors. Equipped with an NVIDIA RTX graphics card, it offers top-notch graphical performance for gaming and content creation. Weighing just 1.8 kg, it is highly portable. The laptop features a NanoEdge display with thin bezels for an immersive viewing experience. With a two-year warranty and a battery life of up to 7 hours, the ASUS ZenBook Pro combines reliability and durability. Priced at 200,000, it caters to users seeking uncompromising performance and a premium display.'},
 {'laptop_description': 'The Acer Predator is a powerhouse laptop designed for gaming enthusiasts. It is equipped with an Intel Core i7 processor clocked at 2.8 GHz, providing exceptional processing power for seamless gaming and demanding tasks. With 16GB of RAM and an SSD, it offers fast and efficient multitasking and storage capabilities. The laptop features a large 17.3" IPS display with a resolution of 1920x1080, delivering stunning visuals and wide viewing angles. It also comes with an NVIDIA GTX graphics card for impressive gaming performance. Weighing 3.2 kg, it is a bit on the heavier side but still offers portability. The laptop features dual cooling fans for effective heat dissipation during intense gaming sessions. With a one-year warranty and a battery life of up to 5 hours, the Acer Predator ensures reliability and endurance. Priced at 80,000, it provides excellent value for gamers seeking powerful gaming performance.'},
 {'laptop_description': 'The Microsoft Surface Laptop is a premium device that combines sleek design with excellent performance. It is powered by an Intel Core i5 processor running at 1.6 GHz, providing efficient computing power for productivity and multimedia tasks. With 8GB of RAM and an SSD, it offers fast and reliable performance along with ample storage capacity. The laptop features a 13.5" PixelSense touchscreen display with a resolution of 2256x1504, delivering vibrant visuals and precise touch input. It comes with Intel Iris Plus integrated graphics for smooth graphics performance. Weighing just 1.3 kg, it is highly portable and suitable for on-the-go usage. The laptop features a touchscreen display, adding versatility to interaction and creativity. With a one-year warranty and an impressive battery life of up to 10 hours, the Microsoft Surface Laptop ensures reliability and all-day productivity. Priced at 90,000, it offers a premium experience for users seeking a stylish and high-performance laptop.'},
 {'laptop_description': 'The Lenovo ThinkPad is a powerful laptop designed for professional users. It is equipped with a Ryzen 7 processor from AMD clocked at 3.0 GHz, providing strong processing capabilities for demanding tasks. With 16GB of RAM and an SSD, it offers smooth multitasking and fast storage access. The laptop features a 14" IPS display with a resolution of 2560x1440, delivering sharp visuals and accurate colors. It also comes with an NVIDIA GTX graphics card for enhanced graphical performance. Weighing just 1.6 kg, it is lightweight and highly portable. The laptop features a backlit keyboard for comfortable typing in low-light environments. With a three-year warranty and a battery life of up to 6 hours, the Lenovo ThinkPad offers reliability and durability. Priced at 60,000, it is an excellent choice for professionals seeking powerful performance and a versatile display.'},
 {'laptop_description': 'The HP Pavilion is a budget-friendly laptop that offers reliable performance for everyday computing tasks. It features an Intel Core i5 processor running at 2.3 GHz, providing decent processing power for productivity and entertainment. With 12GB of RAM and an HDD, it offers a balance between memory capacity and storage space. The laptop sports a 15.6" LCD display with a resolution of 1366x768, offering satisfactory visuals for everyday use. It comes with Intel UHD integrated graphics for basic graphical performance. Weighing 2.1 kg, it strikes a balance between portability and a larger display. The laptop features B&O audio for an enhanced audio experience during multimedia playback. With a one-year warranty and a battery life of up to 4 hours, the HP Pavilion ensures reliable performance for day-to-day tasks. Priced at 30,000, it provides affordability for budget-conscious users seeking'},
 {'laptop_description': 'The ASUS ROG Strix G is a high-performance gaming laptop designed for gamers seeking power and style. It is equipped with an Intel Core i7 processor clocked at 2.9 GHz, providing exceptional processing power for smooth gaming and demanding tasks. With 16GB of RAM and an SSD, it offers fast and efficient multitasking and storage capabilities. The laptop features a large 17.3" IPS display with a resolution of 1920x1080, delivering stunning visuals and wide viewing angles. It comes with an NVIDIA RTX graphics card for immersive gaming performance. Weighing 2.9 kg, it is slightly heavier but still offers portability. The laptop features an Aura Sync RGB keyboard, allowing customizable lighting effects for a personalized gaming setup. With a two-year warranty and a battery life of up to 5 hours, the ASUS ROG Strix G ensures reliability and endurance. Priced at 85,000, it offers excellent value for gamers seeking powerful gaming performance with stylish aesthetics.'},
 {'laptop_description': 'The Dell XPS 15 is a premium laptop that combines powerful performance with a stunning display. It is powered by an Intel Core i9 processor running at 2.8 GHz, offering exceptional processing power for demanding tasks and content creation. With 32GB of RAM and an SSD, it provides ample memory and fast storage access for multitasking and data-intensive applications. The laptop features a 15.6" OLED display with a resolution of 3840x2160, delivering incredibly sharp visuals and vibrant colors. Equipped with an NVIDIA GTX graphics card, it offers excellent graphical performance for gaming and content creation. Weighing just 1.8 kg, it is highly portable. The laptop features an Adobe RGB color gamut, ensuring accurate and vibrant color reproduction for creative professionals. With a three-year warranty and a battery life of up to 8 hours, the Dell XPS 15 combines reliability and durability. Priced at 180,000, it caters to users seeking uncompromising performance and a premium display.'},
 {'laptop_description': 'The Lenovo ThinkPad X1 Carbon is a sleek and lightweight laptop designed for professionals on the go. It is equipped with an Intel Core i7 processor running at 2.6 GHz, providing strong processing capabilities for multitasking and productivity. With 16GB of RAM and an SSD, it offers fast and efficient performance along with ample storage capacity. The laptop features a 14" IPS display with a resolution of 2560x1440, delivering sharp visuals and accurate colors. It comes with Intel UHD integrated graphics for decent graphical performance. Weighing just 1.13 kg, it is extremely lightweight and highly portable. The laptop features an IR camera for face unlock, providing convenient and secure login options. With a three-year warranty and an impressive battery life of up to 12 hours, the Lenovo ThinkPad X1 Carbon ensures reliability and long-lasting productivity. Priced at 130,000, it offers top-notch performance and portability for professionals.'},
 {'laptop_description': 'The Acer Swift 3 is a lightweight and affordable laptop that offers a balance of performance and portability. It features an AMD Ryzen 5 processor clocked at 2.3 GHz, providing reliable processing power for everyday tasks and multimedia consumption. With 8GB of RAM and an SSD, it offers smooth multitasking and fast storage access. The laptop features a 14" IPS display with a resolution of 1920x1080, delivering crisp visuals and wide viewing angles. It comes with an AMD Radeon integrated graphics card for decent graphical performance. Weighing just 1.2 kg, it is incredibly lightweight and highly portable. The laptop features a fingerprint reader for secure and convenient login options. With a one-year warranty and a battery life of up to 9 hours, the Acer Swift 3 ensures reliability and endurance for everyday use. Priced at 50,000, it offers affordability and portability for users seeking a reliable laptop for their daily computing needs.'},
 {'laptop_description': 'The Apple MacBook Air is a sleek and lightweight laptop that offers excellent performance and a seamless user experience. It is powered by the Apple M1 chip clocked at 3.2 GHz, providing powerful and efficient processing capabilities. With 16GB of RAM and an SSD, it offers fast and smooth multitasking along with ample storage space. The laptop features a 13.3" Retina display with a resolution of 2560x1600, delivering sharp and vibrant visuals. It is equipped with the Apple M1 integrated graphics, ensuring smooth graphics performance. Weighing just 1.29 kg, it is highly portable and suitable for on-the-go usage. The laptop features Touch ID, allowing secure and convenient login options. With a three-year warranty and an impressive battery life of up to 14 hours, the Apple MacBook Air ensures reliability and endurance. Priced at 100,000, it offers a premium experience for users seeking a powerful and lightweight laptop with seamless integration into the macOS ecosystem.'},
 {'laptop_description': 'The MSI Prestige 14 is a compact and stylish laptop designed for professionals and content creators. It features an Intel Core i5 processor running at 2.4 GHz, providing reliable performance for multitasking and creative work. With 16GB of RAM and an SSD, it offers fast and responsive performance along with ample storage capacity. The laptop features a 14" IPS display with a resolution of 1920x1080, delivering accurate colors and wide viewing angles. It comes with an NVIDIA GTX graphics card for enhanced graphical performance. Weighing just 1.29 kg, it is highly portable and suitable for on-the-go productivity. The laptop features True Color Technology, ensuring color accuracy for content creation. With a two-year warranty and a battery life of up to 8 hours, the MSI Prestige 14 offers reliability and endurance for professional use. Priced at 70,000, it provides a balance of performance, portability, and affordability.'},
 {'laptop_description': 'The ASUS ZenBook 13 is a lightweight and powerful laptop that offers a premium computing experience. It is equipped with an Intel Core i7 processor running at 2.8 GHz, providing strong processing power for multitasking and productivity. With 16GB of RAM and an SSD, it offers fast and responsive performance along with ample storage capacity. The laptop features a 13.3" NanoEdge display with a resolution of 1920x1080, delivering crisp visuals and immersive viewing. It comes with Intel Iris Xe integrated graphics for smooth graphics performance. Weighing just 1.11 kg, it is incredibly lightweight and highly portable. The laptop features military-grade durability, ensuring durability and reliability. With a two-year warranty and an impressive battery life of up to 11 hours, the ASUS ZenBook 13 offers long-lasting performance and endurance. Priced at 95,000, it provides a premium experience for users seeking a powerful and lightweight laptop.'},
 {'laptop_description': 'The Dell Precision 5550 is a high-performance laptop designed for professionals and creators who require powerful processing capabilities. It is equipped with an Intel Xeon processor running at 2.6 GHz, providing exceptional processing power for demanding tasks and content creation. With 32GB of RAM and an SSD, it offers seamless multitasking and ample storage capacity for large projects. The laptop features a 15.6" OLED display with a resolution of 3840x2160, delivering stunning visuals and accurate color reproduction. It is equipped with an NVIDIA Quadro graphics card, ensuring smooth graphics performance for professional applications. Weighing 1.83 kg, it is lightweight and portable, making it suitable for professionals on the go. The laptop features Thunderbolt 3 connectivity, providing fast data transfer and versatile connectivity options. With a three-year warranty and a battery life of up to 6 hours, the Dell Precision 5550 offers reliability and durability for demanding professional use. Priced at 250,000, it caters to professionals who require uncompromising performance and top-notch display quality.'},
 {'laptop_description': 'The HP ENVY x360 is a versatile 2-in-1 convertible laptop that combines performance and flexibility. It features an Intel Core i7 processor running at 2.8 GHz, providing powerful processing capabilities for multitasking and productivity. With 16GB of RAM and an SSD, it offers fast and efficient performance along with ample storage space. The laptop features a 15.6" IPS display with a resolution of 1920x1080, delivering vibrant visuals and wide viewing angles. It comes with Intel Iris Xe integrated graphics for smooth graphics performance. Weighing 2.05 kg, it offers a good balance between portability and functionality. The laptop features a convertible design, allowing you to switch between laptop and tablet modes for enhanced versatility. With a one-year warranty and a battery life of up to 7 hours, the HP ENVY x360 offers reliability and endurance for everyday use. Priced at 80,000, it provides a versatile computing experience at an affordable price point.'},
 {'laptop_description': 'The Razer Blade 15 is a high-performance gaming laptop that delivers exceptional power and visual excellence. It is powered by an Intel Core i7 processor running at 2.6 GHz, providing robust processing power for demanding gaming and content creation tasks. With 16GB of RAM and an SSD, it offers fast and responsive performance along with ample storage capacity. The laptop features a 15.6" IPS display with a resolution of 1920x1080, delivering vibrant visuals and immersive gaming experiences. It comes with an NVIDIA RTX graphics card for outstanding graphical performance. Weighing 2.09 kg, it strikes a balance between portability and power. The laptop features a Chroma RGB keyboard, allowing customizable lighting effects for a personalized gaming setup. With a one-year warranty and a battery life of up to 6 hours, the Razer Blade 15 ensures reliability and endurance for gaming enthusiasts. Priced at 150,000, it offers a premium gaming experience with powerful performance and eye-catching aesthetics.'},
 {'laptop_description': 'The Apple MacBook Pro is a high-end laptop that combines top-tier performance with a stunning display. It is equipped with an Intel Core i9 processor running at 2.9 GHz, providing exceptional processing power for demanding tasks and content creation. With 32GB of RAM and an SSD, it offers seamless multitasking and fast storage access for large projects. The laptop features a 16" Retina display with a resolution of 3072x1920, delivering breathtaking visuals and precise color reproduction. It comes with an AMD Radeon graphics card, ensuring smooth graphics performance for professional applications. Weighing 2.02 kg, it is relatively lightweight for its size. The laptop features a True Tone display, adjusting the color temperature to match the ambient lighting for a more natural viewing experience. With a three-year warranty and a battery life of up to 10 hours, the Apple MacBook Pro offers reliability and endurance for professionals. Priced at 280,000, it caters to users who require uncompromising performance and a superior display for their demanding workloads.'}]

In [45]:
#mcq2_prompt has two placeholders : description and str
prompt = mcq2_prompt.format(description=laptop_dict[0]['laptop_description'], str=structure)
prompt

'\nLaptop Decription: The Dell Inspiron is a versatile laptop that combines powerful performance and affordability. It features an Intel Core i5 processor clocked at 2.4 GHz, ensuring smooth multitasking and efficient computing. With 8GB of RAM and an SSD, it offers quick data access and ample storage capacity. The laptop sports a vibrant 15.6" LCD display with a resolution of 1920x1080, delivering crisp visuals and immersive viewing experience. Weighing just 2.5 kg, it is highly portable, making it ideal for on-the-go usage. Additionally, it boasts an Intel UHD GPU for decent graphical performance and a backlit keyboard for enhanced typing convenience. With a one-year warranty and a battery life of up to 6 hours, the Dell Inspiron is a reliable companion for work or entertainment. All these features are packed at an affordable price of 35,000, making it an excellent choice for budget-conscious users.\nFrom the laptop decription above, you have to extract relevant values for the following dictionary items. The dictionary structure should be as follows: {\n    "Brand": ___ ,\n    "Model Name": ___ ,\n    "GPU processor": ___ ,\n    "Display Resolution": ___ ,\n    "Weight": ___ ,\n    "Processor": ___ ,\n    "Clock speed": ___ ,\n    "Budget": ___\n}\nTry giving quantitative, absolute, or numerical outputs. Try not to give qualitative or adjective outputs. for example: If the processing speed of a laptop is 2.4GHz, then, in the "processing speed" key, give output as \'2.4GHz\' instead of \'very fast\'.\nExtract only one word values of these properties. Fill in the blanks for each product and output each product\'s dictionary in json format.\n'

In [47]:
values = get_chat_response_mcq2(prompt)

In [48]:
print(values)

{
    "Brand": "Dell",
    "Model Name": "Inspiron",
    "GPU processor": "UHD",
    "Display Resolution": "1920x1080",
    "Weight": "2.5 kg",
    "Processor": "Intel Core i5",
    "Clock speed": "2.4 GHz",
    "Budget": "35,000"
}

In [21]:
# Let's define a function to extract information in JSON format for each laptop description
def extract_information(df_laptop_desc, mcq2_prompt):

  laptop_dict = df_laptop_desc.to_dict(orient='records')

  # Creating an empty list to store the properties
  result = []

  # Get the relevant values for each of the property, key:
  for i in range(len(laptop_dict)):
    prompt = mcq2_prompt.format(description=laptop_dict[i]['laptop_description'], str=structure)
    values = get_chat_response_mcq2(prompt)
    result.append(values)
    # We will print each dictionary property for the current laptop descriptioin
    print(result[i])
  # But in the function output, we are returning the whole list as a whole
  return result

  # Your solution can differ, but your end goal is to output the porperties for all products in one single list

In [22]:
values = extract_information(df, mcq2_prompt)

{
    "Brand": "Dell",
    "Model Name": "Inspiron",
    "GPU processor": "Intel",
    "Display Resolution": "1920x1080",
    "Weight": "2.5 kg",
    "Processor": "Intel Core i5",
    "Clock speed": "2.4 GHz",
    "Budget": "35000"
}
{
    "Brand": "MSI",
    "Model Name": "GL65",
    "GPU processor": "NVIDIA",
    "Display Resolution": "1920x1080",
    "Weight": "2.3 kg",
    "Processor": "Intel",
    "Clock speed": "2.6 GHz",
    "Budget": "55,000"
}

{
    "Brand": "Dell",
    "Model Name": "XPS 15",
    "GPU processor": "NVIDIA",
    "Display Resolution": "3840x2160",
    "Weight": "4.5 lbs",
    "Processor": "Intel",
    "Clock speed": "2.4 GHz",
    "Budget": "90,000"
}

{
    "Brand": "HP",
    "Model Name": "Omen 15",
    "GPU processor": "NVIDIA",
    "Display Resolution": "1920x1080",
    "Weight": "5.2 lbs",
    "Processor": "Intel",
    "Clock speed": "2.3 GHz",
    "Budget": "70,000"
}
{
    "Brand": "HP",
    "Model Name": "EliteBook",
    "GPU processor": "Intel UHD",
    "Display Resolution": "1920x1080",
    "Weight": "1.5",
    "Processor": "Intel",
    "Clock speed": "2.8",
    "Budget": "90000"
}
{
    "Brand": "Lenovo",
    "Model Name": "IdeaPad",
    "GPU processor": "Intel",
    "Display Resolution": "1366x768",
    "Weight": "2.2 kg",
    "Processor": "Intel Core i3",
    "Clock speed": "2.1 GHz",
    "Budget": "25,000"
}
{
    "Brand": "ASUS",
    "Model Name": "ZenBook Pro",
    "GPU processor": "NVIDIA",
    "Display Resolution": "3840x2160",
    "Weight": "1.8kg",
    "Processor": "Intel",
    "Clock speed": "3.1GHz",
    "Budget": "200000"
}
{
    "Brand": "Acer",
    "Model Name": "Predator",
    "GPU Processor": "NVIDIA",
    "Display Resolution": "1920x1080",
    "Weight": "3.2 kg",
    "Processor": "Intel",
    "Clock Speed": "2.8 GHz",
    "Budget": "80,000"
}
{
    "Brand": "Microsoft",
    "Model Name": "Surface",
    "GPU processor": "Intel",
    "Display Resolution": "2256x1504",
    "Weight": "1.3kg",
    "Processor": "Core",
    "Clock speed": "1.6GHz",
    "Budget": "90,000"
}
{
    "Brand": "Lenovo",
    "Model Name": "ThinkPad",
    "GPU processor": "NVIDIA",
    "Display Resolution": "2560x1440",
    "Weight": "1.6kg",
    "Processor": "Ryzen",
    "Clock speed": "3.0GHz",
    "Budget": "60,000"
}
{
    "Brand": "HP",
    "Model Name": "Pavilion",
    "GPU processor": "Intel UHD",
    "Display Resolution": "1366x768",
    "Weight": "2.1 kg",
    "Processor": "Intel Core i5",
    "Clock speed": "2.3 GHz",
    "Budget": "30,000"
}
{
    "Brand": "ASUS",
    "Model Name": "ROG Strix G",
    "GPU processor": "NVIDIA",
    "Display Resolution": "1920x1080",
    "Weight": "2.9kg",
    "Processor": "Intel",
    "Clock speed": "2.9GHz",
    "Budget": "85000"
}
{
    "Brand": "Dell",
    "Model Name": "XPS 15",
    "GPU processor": "NVIDIA",
    "Display Resolution": "3840x2160",
    "Weight": "1.8",
    "Processor": "Intel",
    "Clock speed": "2.8GHz",
    "Budget": "180000"
}
{
    "Brand": "Lenovo",
    "Model Name": "ThinkPad X1 Carbon",
    "GPU processor": "Intel UHD",
    "Display Resolution": "2560x1440",
    "Weight": "1.13kg",
    "Processor": "Intel Core i7",
    "Clock speed": "2.6GHz",
    "Budget": "130000"
}
{
    "Brand": "Acer",
    "Model Name": "Swift 3",
    "GPU processor": "AMD Radeon",
    "Display Resolution": "1920x1080",
    "Weight": "1.2kg",
    "Processor": "AMD Ryzen 5",
    "Clock speed": "2.3GHz",
    "Budget": "50000"
}
{
    "Brand": "Apple",
    "Model Name": "MacBook Air",
    "GPU processor": "integrated",
    "Display Resolution": "2560x1600",
    "Weight": "1.29 kg",
    "Processor": "M1",
    "Clock speed": "3.2 GHz",
    "Budget": "100000"
}
{
    "Brand": "MSI",
    "Model Name": "Prestige 14",
    "GPU processor": "NVIDIA",
    "Display Resolution": "1920x1080",
    "Weight": "1.29kg",
    "Processor": "Intel",
    "Clock speed": "2.4GHz",
    "Budget": "70000"
}
{
    "Brand": "ASUS",
    "Model Name": "ZenBook 13",
    "GPU processor": "Intel Iris Xe",
    "Display Resolution": "1920x1080",
    "Weight": "1.11 kg",
    "Processor": "Intel Core i7",
    "Clock speed": "2.8 GHz",
    "Budget": "95000"
}
{
    "Brand": "Dell",
    "Model Name": "Precision 5550",
    "GPU processor": "NVIDIA Quadro",
    "Display Resolution": "3840x2160",
    "Weight": "1.83 kg",
    "Processor": "Intel Xeon",
    "Clock speed": "2.6 GHz",
    "Budget": "250000"
}
{
    "Brand": "HP",
    "Model Name": "ENVY x360",
    "GPU processor": "Intel Iris Xe",
    "Display Resolution": "1920x1080",
    "Weight": "2.05kg",
    "Processor": "Intel Core i7",
    "Clock speed": "2.8GHz",
    "Budget": "80000"
}
{
    "Brand": "Razer",
    "Model Name": "Blade 15",
    "GPU processor": "NVIDIA",
    "Display Resolution": "1920x1080",
    "Weight": "2.09 kg",
    "Processor": "Intel",
    "Clock speed": "2.6 GHz",
    "Budget": "150000"
}
{
    "Brand": "Apple",
    "Model Name": "MacBook Pro",
    "GPU processor": "AMD Radeon",
    "Display Resolution": "3072x1920",
    "Weight": "2.02 kg",
    "Processor": "Intel Core i9",
    "Clock speed": "2.9 GHz",
    "Budget": "280000"
}

In [24]:
print(type(values))

<class 'list'>

In [25]:
print(values[0])

{
    "Brand": "Dell",
    "Model Name": "Inspiron",
    "GPU processor": "Intel",
    "Display Resolution": "1920x1080",
    "Weight": "2.5 kg",
    "Processor": "Intel Core i5",
    "Clock speed": "2.4 GHz",
    "Budget": "35000"
}

In [27]:
print(values[0])

{
    "Brand": "Dell",
    "Model Name": "Inspiron",
    "GPU processor": "Intel",
    "Display Resolution": "1920x1080",
    "Weight": "2.5 kg",
    "Processor": "Intel Core i5",
    "Clock speed": "2.4 GHz",
    "Budget": "35000"
}

#Usecase 3: Combinig usecase 1 and usecase 2
Assign laptop category from description and include it in the laptop properties

# Create a structure to include category

Combine mcq1_prompt and mcq2_promt to get all details in single structure

In [96]:
laptop_properties = '''{
  "Category": ___ ,
  "Brand": ___ ,
  "Model Name": ___ ,
  "GPU processor": ___ ,
  "Display Resolution": ___ ,
  "Weight": ___ ,"Processor": ___ ,
  "Clock speed": ___ ,
  "Budget": ___}
  '''

In [97]:
mcq3_prompt = '''
Laptop Decription: {description}
From the laptop decription above, you have to extract relevant values for the laptop properties for the following dictionary items. The dictionary structure should be as follows: {properties}
For the first property 'Category', you have to identify what role does the laptop serve. Refer to the key value pairs of categories and category details below. Identify which of the following details does the product description fits best and assign that category to that latpop. \n
Categories:
[
    'general': 'For general purpose use such as light web browsing, editing documents etc.'
    'business': 'For business users, the focus is on portability, battery backup and general purpose use.'
    'gamer': 'For gamers, the focus is primarily on high-performance, high-end graphics requirement, efficient processor etc.'
    'programmer': 'For programmers, the focus is on performance, battery backup, high-end RAM etc.'
    'multimedia': 'For multimedia use cases, the requirements are a good quality/ high resolution display, wide screens, good audio and video quality, battery backup, efficiency etc.' # Write the prompt here
] \n
For the reamining properties try giving quantitative, absolute, or numerical outputs. Try not to give qualitative or adjective outputs. For example: If the processing speed of a laptop is 2.4GHz, then, in the "processing speed" key, give output as '2.4GHz' instead of 'very fast'.
Extract only one word values of these properties. Fill in the blanks for each product and output each product's dictionary in json format. The output dictionary should have no special characters, it should contain key and values paris containing only characters and/or numbers.
'''

# get chat response

In [98]:
# Best practice
import openai
from tenacity import retry, wait_random_exponential, stop_after_attempt

# Retry up to 6 times with exponential backoff, starting at 1 second and maxing out at 20 seconds delay
@retry(wait=wait_random_exponential(min=1, max=20), stop=stop_after_attempt(6))
def get_chat_response_mcq3(user_request):

  MODEL = 'gpt-3.5-turbo-16k'# Define GPT model

  SYSTEM_MESSAGE = 'You are a helpful shopping assitant.'# Default System Message

  try:
  # Define the list of messages
    messages = [
        {'role': 'system', 'content': SYSTEM_MESSAGE},
        {'role': 'user', 'content': user_request}
    ]

# Get the ChatCompletion Response from the GPT-3.5 model
    response = openai.chat.completions.create(
        model = MODEL,
        messages = messages,
        #response_format = {'type': 'json_object'}
    )

    response_content = response.choices[0].message.content
    # Parse the response_content from the message

    return response_content

  # Raise exception error
  except Exception as e:
    print(f"An error occurred: {e}")
    return None

## Testing for one laptop description

In [99]:
laptop_df = df.copy()
laptop_df.head()

                                  laptop_description
0  The Dell Inspiron is a versatile laptop that c...
1  The MSI GL65 is a high-performance laptop desi...
2  The HP EliteBook is a premium laptop designed ...
3  The Lenovo IdeaPad is a versatile laptop that ...
4  The ASUS ZenBook Pro is a high-end laptop that...

In [100]:
laptop_dict = laptop_df.to_dict(orient='records')
type(laptop_dict)

list

In [101]:
len(laptop_dict)

20

In [102]:
# access the first description form the list of descriptions
laptop_dict[7]['laptop_description']

'The Lenovo ThinkPad is a powerful laptop designed for professional users. It is equipped with a Ryzen 7 processor from AMD clocked at 3.0 GHz, providing strong processing capabilities for demanding tasks. With 16GB of RAM and an SSD, it offers smooth multitasking and fast storage access. The laptop features a 14" IPS display with a resolution of 2560x1440, delivering sharp visuals and accurate colors. It also comes with an NVIDIA GTX graphics card for enhanced graphical performance. Weighing just 1.6 kg, it is lightweight and highly portable. The laptop features a backlit keyboard for comfortable typing in low-light environments. With a three-year warranty and a battery life of up to 6 hours, the Lenovo ThinkPad offers reliability and durability. Priced at 60,000, it is an excellent choice for professionals seeking powerful performance and a versatile display.'

In [103]:
# append the description to the mcq1_promt which has categories defined
prompt = mcq3_prompt.format(description=laptop_dict[7]['laptop_description'], properties=laptop_properties)
prompt

'\nLaptop Decription: The Lenovo ThinkPad is a powerful laptop designed for professional users. It is equipped with a Ryzen 7 processor from AMD clocked at 3.0 GHz, providing strong processing capabilities for demanding tasks. With 16GB of RAM and an SSD, it offers smooth multitasking and fast storage access. The laptop features a 14" IPS display with a resolution of 2560x1440, delivering sharp visuals and accurate colors. It also comes with an NVIDIA GTX graphics card for enhanced graphical performance. Weighing just 1.6 kg, it is lightweight and highly portable. The laptop features a backlit keyboard for comfortable typing in low-light environments. With a three-year warranty and a battery life of up to 6 hours, the Lenovo ThinkPad offers reliability and durability. Priced at 60,000, it is an excellent choice for professionals seeking powerful performance and a versatile display.\nFrom the laptop decription above, you have to extract relevant values for the laptop properties for the following dictionary items. The dictionary structure should be as follows: {\n  "Category": ___ ,\n  "Brand": ___ ,\n  "Model Name": ___ ,\n  "GPU processor": ___ ,\n  "Display Resolution": ___ ,\n  "Weight": ___ ,"Processor": ___ ,\n  "Clock speed": ___ ,\n  "Budget": ___}\n  \nFor the first property \'Category\', you have to identify what role does the laptop serve. Refer to the key value pairs of categories and category details below. Identify which of the following details does the product description fits best and assign that category to that latpop. \n\nCategories:\n[\n    \'general\': \'For general purpose use such as light web browsing, editing documents etc.\'\n    \'business\': \'For business users, the focus is on portability, battery backup and general purpose use.\'\n    \'gamer\': \'For gamers, the focus is primarily on high-performance, high-end graphics requirement, efficient processor etc.\'\n    \'programmer\': \'For programmers, the focus is on performance, battery backup, high-end RAM etc.\'\n    \'multimedia\': \'For multimedia use cases, the requirements are a good quality/ high resolution display, wide screens, good audio and video quality, battery backup, efficiency etc.\' # Write the prompt here\n] \n\nFor the reamining properties try giving quantitative, absolute, or numerical outputs. Try not to give qualitative or adjective outputs. For example: If the processing speed of a laptop is 2.4GHz, then, in the "processing speed" key, give output as \'2.4GHz\' instead of \'very fast\'.\nExtract only one word values of these properties. Fill in the blanks for each product and output each product\'s dictionary in json format. The output dictionary should have no special characters, it should contain key and values paris containing only characters and/or numbers.\n'

In [104]:
values = get_chat_response_mcq3(prompt)

In [105]:
print(values)

{
  "Category": "business",
  "Brand": "Lenovo",
  "Model Name": "ThinkPad",
  "GPU processor": "NVIDIA",
  "Display Resolution": "2560x1440",
  "Weight": "1.6kg",
  "Processor": "Ryzen",
  "Clock speed": "3.0GHz",
  "Budget": "60000"
}

## Return the properties for all the laptop descriptions

We have tested the response for the first laptop property, let's call the gpt to return for each laptop description in a loop.

In [106]:
def extract_information(df_laptop_description,mcq3_prompt):

  #laptop_df = df.copy()
  laptop_dict = df_laptop_description.to_dict(orient ='records')

  # Creating an empty list to store the properties
  result = []

  # Get the relevant values for each of the property:
  for i in range(len(laptop_dict)):
    prompt = mcq3_prompt.format(description=laptop_dict[i]['laptop_description'], properties=laptop_properties)
    values = get_chat_response_mcq3(prompt)
    result.append(values)
    # Print each of the dictionary of properties
    print(f"For description # {i} : {result[i]}")
    #print(result[i])
  # But in the function output, we are returning the whole list as a whole.
  return result

In [107]:
all_laptop_properties = extract_information(df, mcq3_prompt)

For description # 0 : {
  "Category": "general",
  "Brand": "Dell",
  "Model Name": "Inspiron",
  "GPU processor": "Intel",
  "Display Resolution": "1920x1080",
  "Weight": "2.5",
  "Processor": "Intel Core i5",
  "Clock speed": "2.4 GHz",
  "Budget": "35000"
}
For description # 1 : {
  "Category": "gamer",
  "Brand": "MSI",
  "Model Name": "GL65",
  "GPU processor": "NVIDIA",
  "Display Resolution": "1920x1080",
  "Weight": "2.3",
  "Processor": "Intel",
  "Clock speed": "2.6",
  "Budget": "55000"
}
For description # 2 : {
  "Category": "business",
  "Brand": "HP",
  "Model Name": "EliteBook",
  "GPU processor": "Intel UHD",
  "Display Resolution": "1920x1080",
  "Weight": "1.5",
  "Processor": "Intel",
  "Clock speed": "2.8",
  "Budget": "90000"
}
For description # 3 : {
  "Category": "general",
  "Brand": "Lenovo",
  "Model Name": "IdeaPad",
  "GPU processor": "Intel UHD",
  "Display Resolution": "1366x768",
  "Weight": "2.2kg",
  "Processor": "Intel Core i3",
  "Clock speed": "2.1GHz",
  "Budget": "25000"
}
For description # 4 : {
  "Category": "gamer",
  "Brand": "ASUS",
  "Model Name": "ZenBook Pro",
  "GPU processor": "NVIDIA RTX",
  "Display Resolution": "3840x2160",
  "Weight": "1.8kg",
  "Processor": "Intel Core i9",
  "Clock speed": "3.1GHz",
  "Budget": "200000"
}
For description # 5 : {
  "Category": "gamer",
  "Brand": "Acer",
  "Model Name": "Predator",
  "GPU processor": "NVIDIA",
  "Display Resolution": "1920x1080",
  "Weight": "3.2kg",
  "Processor": "Intel",
  "Clock speed": "2.8GHz",
  "Budget": "80000"
}
For description # 6 : {
  "Category": "general",
  "Brand": "Microsoft",
  "Model Name": "Surface Laptop",
  "GPU processor": "Intel Iris Plus",
  "Display Resolution": "2256x1504",
  "Weight": "1.3kg",
  "Processor": "Core i5",
  "Clock speed": "1.6GHz",
  "Budget": "90000"
}
For description # 7 : {
  "Category": "business",
  "Brand": "Lenovo",
  "Model Name": "ThinkPad",
  "GPU Processor": "NVIDIA",
  "Display Resolution": "2560x1440",
  "Weight": "1.6kg",
  "Processor": "Ryzen",
  "Clock Speed": "3.0GHz",
  "Budget": "60000"
}
For description # 8 : {
  "Category": "general",
  "Brand": "HP",
  "Model Name": "Pavilion",
  "GPU processor": "Intel UHD",
  "Display Resolution": "1366x768",
  "Weight": "2.1",
  "Processor": "Intel Core i5",
  "Clock speed": "2.3 GHz",
  "Budget": "30,000"
}
For description # 9 : {
  "Category": "gamer",
  "Brand": "ASUS",
  "Model Name": "ROG Strix G",
  "GPU processor": "NVIDIA RTX",
  "Display Resolution": "1920x1080",
  "Weight": "2.9kg",
  "Processor": "Intel Core i7",
  "Clock speed": "2.9GHz",
  "Budget": "85000"
}
For description # 10 : {
  "Category": "gamer",
  "Brand": "Dell",
  "Model Name": "XPS 15",
  "GPU processor": "NVIDIA",
  "Display Resolution": "3840x2160",
  "Weight": "1.8",
  "Processor": "Intel",
  "Clock speed": "2.8",
  "Budget": "180000"
}
For description # 11 : {"Category": "business", "Brand": "Lenovo", "Model Name": "ThinkPad X1 Carbon", "GPU processor": "Intel UHD", "Display Resolution": "2560x1440", "Weight": "1.13", "Processor": "Intel Core i7", "Clock speed": "2.6 GHz", "Budget": "130000"}
For description # 12 : {
  "Category": "general",
  "Brand": "Acer",
  "Model Name": "Swift 3",
  "GPU processor": "Radeon",
  "Display Resolution": "1920x1080",
  "Weight": "1.2kg",
  "Processor": "AMD Ryzen 5",
  "Clock speed": "2.3GHz",
  "Budget": "50000"
}
For description # 13 : {
  "Category": "general",
  "Brand": "Apple",
  "Model Name": "MacBook Air",
  "GPU processor": "Apple M1",
  "Display Resolution": "2560x1600",
  "Weight": "1.29",
  "Processor": "Apple M1",
  "Clock speed": "3.2",
  "Budget": "100000"
}
For description # 14 : {
  "Category": "business",
  "Brand": "MSI",
  "Model Name": "Prestige 14",
  "GPU processor": "NVIDIA",
  "Display Resolution": "1920x1080",
  "Weight": "1.29kg",
  "Processor": "Intel",
  "Clock speed": "2.4GHz",
  "Budget": "70000"
}
For description # 15 : {
  "Category": "general",
  "Brand": "ASUS",
  "Model Name": "ZenBook 13",
  "GPU processor": "Intel Iris Xe",
  "Display Resolution": "1920x1080",
  "Weight": "1.11",
  "Processor": "Intel Core i7",
  "Clock speed": "2.8 GHz",
  "Budget": "95000"
}
For description # 16 : {
  "Category": "workstation",
  "Brand": "Dell",
  "Model Name": "Precision 5550",
  "GPU processor": "NVIDIA Quadro",
  "Display Resolution": "3840x2160",
  "Weight": "1.83 kg",
  "Processor": "Intel Xeon",
  "Clock speed": "2.6 GHz",
  "Budget": "250000"
}
For description # 17 : {
  "Category": "general",
  "Brand": "HP",
  "Model Name": "ENVY x360",
  "GPU processor": "Intel Iris Xe",
  "Display Resolution": "1920x1080",
  "Weight": "2.05 kg",
  "Processor": "Intel Core i7",
  "Clock speed": "2.8 GHz",
  "Budget": "80000"
}
For description # 18 : {
  "Category": "gamer",
  "Brand": "Razer",
  "Model Name": "Blade 15",
  "GPU processor": "NVIDIA RTX",
  "Display Resolution": "1920x1080",
  "Weight": "2.09kg",
  "Processor": "Intel Core i7",
  "Clock speed": "2.6GHz",
  "Budget": "150000"
}
For description # 19 : {
  "Category": "gamer",
  "Brand": "Apple",
  "Model Name": "MacBook Pro",
  "GPU processor": "AMD",
  "Display Resolution": "3072x1920",
  "Weight": "2.02",
  "Processor": "Intel",
  "Clock speed": "2.9",
  "Budget": "280000"
}

# To Do
Convert the string of dictionaries into a JSON format and create csv file with keys as header

In [108]:
print(all_laptop_properties)

['{\n  "Category": "general",\n  "Brand": "Dell",\n  "Model Name": "Inspiron",\n  "GPU processor": "Intel",\n  "Display Resolution": "1920x1080",\n  "Weight": "2.5",\n  "Processor": "Intel Core i5",\n  "Clock speed": "2.4 GHz",\n  "Budget": "35000"\n}', '{\n  "Category": "gamer",\n  "Brand": "MSI",\n  "Model Name": "GL65",\n  "GPU processor": "NVIDIA",\n  "Display Resolution": "1920x1080",\n  "Weight": "2.3",\n  "Processor": "Intel",\n  "Clock speed": "2.6",\n  "Budget": "55000"\n}', '{\n  "Category": "business",\n  "Brand": "HP",\n  "Model Name": "EliteBook",\n  "GPU processor": "Intel UHD",\n  "Display Resolution": "1920x1080",\n  "Weight": "1.5",\n  "Processor": "Intel",\n  "Clock speed": "2.8",\n  "Budget": "90000"\n}', '{\n  "Category": "general",\n  "Brand": "Lenovo",\n  "Model Name": "IdeaPad",\n  "GPU processor": "Intel UHD",\n  "Display Resolution": "1366x768",\n  "Weight": "2.2kg",\n  "Processor": "Intel Core i3",\n  "Clock speed": "2.1GHz",\n  "Budget": "25000"\n}', '{\n  "Category": "gamer",\n  "Brand": "ASUS",\n  "Model Name": "ZenBook Pro",\n  "GPU processor": "NVIDIA RTX",\n  "Display Resolution": "3840x2160",\n  "Weight": "1.8kg",\n  "Processor": "Intel Core i9",\n  "Clock speed": "3.1GHz",\n  "Budget": "200000"\n}', '{\n  "Category": "gamer",\n  "Brand": "Acer",\n  "Model Name": "Predator",\n  "GPU processor": "NVIDIA",\n  "Display Resolution": "1920x1080",\n  "Weight": "3.2kg",\n  "Processor": "Intel",\n  "Clock speed": "2.8GHz",\n  "Budget": "80000"\n}', '{\n  "Category": "general",\n  "Brand": "Microsoft",\n  "Model Name": "Surface Laptop",\n  "GPU processor": "Intel Iris Plus",\n  "Display Resolution": "2256x1504",\n  "Weight": "1.3kg",\n  "Processor": "Core i5",\n  "Clock speed": "1.6GHz",\n  "Budget": "90000"\n}', '{\n  "Category": "business",\n  "Brand": "Lenovo",\n  "Model Name": "ThinkPad",\n  "GPU Processor": "NVIDIA",\n  "Display Resolution": "2560x1440",\n  "Weight": "1.6kg",\n  "Processor": "Ryzen",\n  "Clock Speed": "3.0GHz",\n  "Budget": "60000"\n}', '{\n  "Category": "general",\n  "Brand": "HP",\n  "Model Name": "Pavilion",\n  "GPU processor": "Intel UHD",\n  "Display Resolution": "1366x768",\n  "Weight": "2.1",\n  "Processor": "Intel Core i5",\n  "Clock speed": "2.3 GHz",\n  "Budget": "30,000"\n}', '{\n  "Category": "gamer",\n  "Brand": "ASUS",\n  "Model Name": "ROG Strix G",\n  "GPU processor": "NVIDIA RTX",\n  "Display Resolution": "1920x1080",\n  "Weight": "2.9kg",\n  "Processor": "Intel Core i7",\n  "Clock speed": "2.9GHz",\n  "Budget": "85000"\n}', '{\n  "Category": "gamer",\n  "Brand": "Dell",\n  "Model Name": "XPS 15",\n  "GPU processor": "NVIDIA",\n  "Display Resolution": "3840x2160",\n  "Weight": "1.8",\n  "Processor": "Intel",\n  "Clock speed": "2.8",\n  "Budget": "180000"\n}', '{"Category": "business", "Brand": "Lenovo", "Model Name": "ThinkPad X1 Carbon", "GPU processor": "Intel UHD", "Display Resolution": "2560x1440", "Weight": "1.13", "Processor": "Intel Core i7", "Clock speed": "2.6 GHz", "Budget": "130000"}', '{\n  "Category": "general",\n  "Brand": "Acer",\n  "Model Name": "Swift 3",\n  "GPU processor": "Radeon",\n  "Display Resolution": "1920x1080",\n  "Weight": "1.2kg",\n  "Processor": "AMD Ryzen 5",\n  "Clock speed": "2.3GHz",\n  "Budget": "50000"\n}', '{\n  "Category": "general",\n  "Brand": "Apple",\n  "Model Name": "MacBook Air",\n  "GPU processor": "Apple M1",\n  "Display Resolution": "2560x1600",\n  "Weight": "1.29",\n  "Processor": "Apple M1",\n  "Clock speed": "3.2",\n  "Budget": "100000"\n}', '{\n  "Category": "business",\n  "Brand": "MSI",\n  "Model Name": "Prestige 14",\n  "GPU processor": "NVIDIA",\n  "Display Resolution": "1920x1080",\n  "Weight": "1.29kg",\n  "Processor": "Intel",\n  "Clock speed": "2.4GHz",\n  "Budget": "70000"\n}', '{\n  "Category": "general",\n  "Brand": "ASUS",\n  "Model Name": "ZenBook 13",\n  "GPU processor": "Intel Iris Xe",\n  "Display Resolution": "1920x1080",\n  "Weight": "1.11",\n  "Processor": "Intel Core i7",\n  "Clock speed": "2.8 GHz",\n  "Budget": "95000"\n}', '{\n  "Category": "workstation",\n  "Brand": "Dell",\n  "Model Name": "Precision 5550",\n  "GPU processor": "NVIDIA Quadro",\n  "Display Resolution": "3840x2160",\n  "Weight": "1.83 kg",\n  "Processor": "Intel Xeon",\n  "Clock speed": "2.6 GHz",\n  "Budget": "250000"\n}', '{\n  "Category": "general",\n  "Brand": "HP",\n  "Model Name": "ENVY x360",\n  "GPU processor": "Intel Iris Xe",\n  "Display Resolution": "1920x1080",\n  "Weight": "2.05 kg",\n  "Processor": "Intel Core i7",\n  "Clock speed": "2.8 GHz",\n  "Budget": "80000"\n}', '{\n  "Category": "gamer",\n  "Brand": "Razer",\n  "Model Name": "Blade 15",\n  "GPU processor": "NVIDIA RTX",\n  "Display Resolution": "1920x1080",\n  "Weight": "2.09kg",\n  "Processor": "Intel Core i7",\n  "Clock speed": "2.6GHz",\n  "Budget": "150000"\n}', '{\n  "Category": "gamer",\n  "Brand": "Apple",\n  "Model Name": "MacBook Pro",\n  "GPU processor": "AMD",\n  "Display Resolution": "3072x1920",\n  "Weight": "2.02",\n  "Processor": "Intel",\n  "Clock speed": "2.9",\n  "Budget": "280000"\n}']

In [83]:
type(all_laptop_properties)

list

In [86]:
type(all_laptop_properties[0])

str

In [109]:
all_laptop_properties[0]

'{\n  "Category": "general",\n  "Brand": "Dell",\n  "Model Name": "Inspiron",\n  "GPU processor": "Intel",\n  "Display Resolution": "1920x1080",\n  "Weight": "2.5",\n  "Processor": "Intel Core i5",\n  "Clock speed": "2.4 GHz",\n  "Budget": "35000"\n}'

In [110]:
all_laptop_properties[0].replace("\\n", "").replace("\\", "").replace("  ", "").replace("\n", "")

'{"Category": "general","Brand": "Dell","Model Name": "Inspiron","GPU processor": "Intel","Display Resolution": "1920x1080","Weight": "2.5","Processor": "Intel Core i5","Clock speed": "2.4 GHz","Budget": "35000"}'

In [89]:
str1 = all_laptop_properties[0].replace("\\n", "").replace("\\", "").replace("  ", "").replace("\n", "")
print(str1)
print(type(str1))

{"Category": "general","Brand": "Dell","Model Name": "Inspiron","GPU processor": "Intel","Display Resolution": "1920x1080","Weight": "2.5kg","Processor": "Intel","Clock speed": "2.4GHz","Budget": "35000"}
<class 'str'>

In [47]:
len(all_laptop_properties)

20

In [60]:
all_laptop_properties[0]

'{\n    "Category": "general",\n    "Brand": "Dell",\n    "Model Name": "Inspiron",\n    "GPU processor": "Intel",\n    "Display Resolution": "1920x1080",\n    "Weight": "2.5kg",\n    "Processor": "Intel",\n    "Clock speed": "2.4GHz",\n    "Budget": "35000"\n}'

In [61]:
all_laptop_properties

['{\n    "Category": "general",\n    "Brand": "Dell",\n    "Model Name": "Inspiron",\n    "GPU processor": "Intel",\n    "Display Resolution": "1920x1080",\n    "Weight": "2.5kg",\n    "Processor": "Intel",\n    "Clock speed": "2.4GHz",\n    "Budget": "35000"\n}',
 '{\n    "Category": "gamer",\n    "Brand": "MSI",\n    "Model Name": "GL65",\n    "GPU processor": "NVIDIA",\n    "Display Resolution": "1920x1080",\n    "Weight": "2.3kg",\n    "Processor": "Intel",\n    "Clock speed": "2.6GHz",\n    "Budget": "55,000"\n}',
 '{\n    "Category": "business",\n    "Brand": "HP",\n    "Model Name": "EliteBook",\n    "GPU processor": "Intel",\n    "Display Resolution": "1920x1080",\n    "Weight": "1.5kg",\n    "Processor": "Intel Core i7",\n    "Clock speed": "2.8GHz",\n    "Budget": "90,000"\n}',
 '{\n  "Category": "general",\n  "Brand": "Lenovo",\n  "Model Name": "IdeaPad",\n  "GPU processor": "Intel UHD",\n  "Display Resolution": "1366x768",\n  "Weight": "2.2kg",\n  "Processor": "Intel Core i3",\n  "Clock speed": "2.1GHz",\n  "Budget": "25000"\n}',
 '{\n    "Category": "gamer",\n    "Brand": "ASUS",\n    "Model Name": "ZenBook Pro",\n    "GPU Processor": "NVIDIA",\n    "Display Resolution": "3840x2160",\n    "Weight": "1.8kg",\n    "Processor": "Intel",\n    "Clock Speed": "3.1GHz",\n    "Budget": "200000"\n}',
 '{\n  "Category": "gamer",\n  "Brand": "Acer",\n  "Model Name": "Predator",\n  "GPU processor": "NVIDIA",\n  "Display Resolution": "1920x1080",\n  "Weight": "3.2kg",\n  "Processor": "Intel",\n  "Clock speed": "2.8GHz",\n  "Budget": "80000"\n}',
 '{\n    "Category": "general",\n    "Brand": "Microsoft",\n    "Model Name": "Surface Laptop",\n    "GPU processor": "Intel Iris Plus",\n    "Display Resolution": "2256x1504",\n    "Weight": "1.3kg",\n    "Processor": "Intel Core i5",\n    "Clock speed": "1.6GHz",\n    "Budget": "90,000"\n}',
 '{\n    "Category": "business",\n    "Brand": "Lenovo",\n    "Model Name": "ThinkPad",\n    "GPU processor": "NVIDIA",\n    "Display Resolution": "2560x1440",\n    "Weight": "1.6kg",\n    "Processor": "Ryzen",\n    "Clock speed": "3.0GHz",\n    "Budget": "60,000"\n}',
 '{\n    "Category": "general",\n    "Brand": "HP",\n    "Model Name": "Pavilion",\n    "GPU processor": "Intel UHD",\n    "Display Resolution": "1366x768",\n    "Weight": "2.1",\n    "Processor": "Intel",\n    "Clock speed": "2.3",\n    "Budget": "30,000"\n}',
 '{\n    "Category": "gamer",\n    "Brand": "ASUS",\n    "Model Name": "ROG Strix G",\n    "GPU processor": "NVIDIA",\n    "Display Resolution": "1920x1080",\n    "Weight": "2.9",\n    "Processor": "Intel",\n    "Clock speed": "2.9",\n    "Budget": "85000"\n}',
 '{\n    "Category": "gamer",\n    "Brand": "Dell",\n    "Model Name": "XPS 15",\n    "GPU processor": "NVIDIA",\n    "Display Resolution": "3840x2160",\n    "Weight": "1.8kg",\n    "Processor": "Intel",\n    "Clock speed": "2.8GHz",\n    "Budget": "180000"\n}',
 '{\n    "Category": "business",\n    "Brand": "Lenovo",\n    "Model Name": "ThinkPad X1 Carbon",\n    "GPU processor": "Intel",\n    "Display Resolution": "2560x1440",\n    "Weight": "1.13kg",\n    "Processor": "Intel Core i7",\n    "Clock speed": "2.6GHz",\n    "Budget": "130000"\n}',
 '{\n    "Category": "general",\n    "Brand": "Acer",\n    "Model Name": "Swift 3",\n    "GPU processor": "Radeon",\n    "Display Resolution": "1920x1080",\n    "Weight": "1.2kg",\n    "Processor": "Ryzen",\n    "Clock speed": "2.3GHz",\n    "Budget": "50000"\n}',
 '{\n    "Category": "general",\n    "Brand": "Apple",\n    "Model Name": "MacBook Air",\n    "GPU processor": "M1",\n    "Display Resolution": "2560x1600",\n    "Weight": "1.29kg",\n    "Processor": "Apple M1",\n    "Clock speed": "3.2GHz",\n    "Budget": "100000"\n}',
 '{\n    "Category": "business",\n    "Brand": "MSI",\n    "Model Name": "Prestige 14",\n    "GPU processor": "NVIDIA",\n    "Display Resolution": "1920x1080",\n    "Weight": "1.29kg",\n    "Processor": "Intel",\n    "Clock speed": "2.4GHz",\n    "Budget": "70000"\n}',
 '{\n    "Category": "business",\n    "Brand": "ASUS",\n    "Model Name": "ZenBook 13",\n    "GPU processor": "Intel Iris Xe",\n    "Display Resolution": "1920x1080",\n    "Weight": "1.11kg",\n    "Processor": "Intel Core i7",\n    "Clock speed": "2.8GHz",\n    "Budget": "95000"\n}',
 '{\n    "Category": "business",\n    "Brand": "Dell",\n    "Model Name": "Precision 5550",\n    "GPU processor": "NVIDIA Quadro",\n    "Display Resolution": "3840x2160",\n    "Weight": "1.83kg",\n    "Processor": "Intel Xeon",\n    "Clock speed": "2.6GHz",\n    "Budget": "250000"\n}',
 '{\n    "Category": "general",\n    "Brand": "HP",\n    "Model Name": "ENVY x360",\n    "GPU processor": "Intel Iris Xe",\n    "Display Resolution": "1920x1080",\n    "Weight": "2.05 kg",\n    "Processor": "Intel Core i7",\n    "Clock speed": "2.8 GHz",\n    "Budget": "80000"\n}',
 '{\n    "Category": "gamer",\n    "Brand": "Razer",\n    "Model Name": "Blade 15",\n    "GPU processor": "NVIDIA RTX",\n    "Display Resolution": "1920x1080",\n    "Weight": "2.09kg",\n    "Processor": "Intel",\n    "Clock speed": "2.6GHz",\n    "Budget": "150000"\n}',
 '{\n    "Category": "business",\n    "Brand": "Apple",\n    "Model Name": "MacBook Pro",\n    "GPU processor": "AMD",\n    "Display Resolution": "3072x1920",\n    "Weight": "2.02 kg",\n    "Processor": "Intel",\n    "Clock speed": "2.9 GHz",\n    "Budget": "280000"\n}']

In [62]:
import json

In [79]:
data = all_laptop_properties

In [80]:
# convert list of dictionaries to JSON
json_data = json.dumps(data)
print(json_data)

["{\n    \"Category\": \"general\",\n    \"Brand\": \"Dell\",\n    \"Model Name\": \"Inspiron\",\n    \"GPU processor\": \"Intel\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"2.5kg\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.4GHz\",\n    \"Budget\": \"35000\"\n}", "{\n    \"Category\": \"gamer\",\n    \"Brand\": \"MSI\",\n    \"Model Name\": \"GL65\",\n    \"GPU processor\": \"NVIDIA\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"2.3kg\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.6GHz\",\n    \"Budget\": \"55,000\"\n}", "{\n    \"Category\": \"business\",\n    \"Brand\": \"HP\",\n    \"Model Name\": \"EliteBook\",\n    \"GPU processor\": \"Intel\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"1.5kg\",\n    \"Processor\": \"Intel Core i7\",\n    \"Clock speed\": \"2.8GHz\",\n    \"Budget\": \"90,000\"\n}", "{\n  \"Category\": \"general\",\n  \"Brand\": \"Lenovo\",\n  \"Model Name\": \"IdeaPad\",\n  \"GPU processor\": \"Intel UHD\",\n  \"Display Resolution\": \"1366x768\",\n  \"Weight\": \"2.2kg\",\n  \"Processor\": \"Intel Core i3\",\n  \"Clock speed\": \"2.1GHz\",\n  \"Budget\": \"25000\"\n}", "{\n    \"Category\": \"gamer\",\n    \"Brand\": \"ASUS\",\n    \"Model Name\": \"ZenBook Pro\",\n    \"GPU Processor\": \"NVIDIA\",\n    \"Display Resolution\": \"3840x2160\",\n    \"Weight\": \"1.8kg\",\n    \"Processor\": \"Intel\",\n    \"Clock Speed\": \"3.1GHz\",\n    \"Budget\": \"200000\"\n}", "{\n  \"Category\": \"gamer\",\n  \"Brand\": \"Acer\",\n  \"Model Name\": \"Predator\",\n  \"GPU processor\": \"NVIDIA\",\n  \"Display Resolution\": \"1920x1080\",\n  \"Weight\": \"3.2kg\",\n  \"Processor\": \"Intel\",\n  \"Clock speed\": \"2.8GHz\",\n  \"Budget\": \"80000\"\n}", "{\n    \"Category\": \"general\",\n    \"Brand\": \"Microsoft\",\n    \"Model Name\": \"Surface Laptop\",\n    \"GPU processor\": \"Intel Iris Plus\",\n    \"Display Resolution\": \"2256x1504\",\n    \"Weight\": \"1.3kg\",\n    \"Processor\": \"Intel Core i5\",\n    \"Clock speed\": \"1.6GHz\",\n    \"Budget\": \"90,000\"\n}", "{\n    \"Category\": \"business\",\n    \"Brand\": \"Lenovo\",\n    \"Model Name\": \"ThinkPad\",\n    \"GPU processor\": \"NVIDIA\",\n    \"Display Resolution\": \"2560x1440\",\n    \"Weight\": \"1.6kg\",\n    \"Processor\": \"Ryzen\",\n    \"Clock speed\": \"3.0GHz\",\n    \"Budget\": \"60,000\"\n}", "{\n    \"Category\": \"general\",\n    \"Brand\": \"HP\",\n    \"Model Name\": \"Pavilion\",\n    \"GPU processor\": \"Intel UHD\",\n    \"Display Resolution\": \"1366x768\",\n    \"Weight\": \"2.1\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.3\",\n    \"Budget\": \"30,000\"\n}", "{\n    \"Category\": \"gamer\",\n    \"Brand\": \"ASUS\",\n    \"Model Name\": \"ROG Strix G\",\n    \"GPU processor\": \"NVIDIA\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"2.9\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.9\",\n    \"Budget\": \"85000\"\n}", "{\n    \"Category\": \"gamer\",\n    \"Brand\": \"Dell\",\n    \"Model Name\": \"XPS 15\",\n    \"GPU processor\": \"NVIDIA\",\n    \"Display Resolution\": \"3840x2160\",\n    \"Weight\": \"1.8kg\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.8GHz\",\n    \"Budget\": \"180000\"\n}", "{\n    \"Category\": \"business\",\n    \"Brand\": \"Lenovo\",\n    \"Model Name\": \"ThinkPad X1 Carbon\",\n    \"GPU processor\": \"Intel\",\n    \"Display Resolution\": \"2560x1440\",\n    \"Weight\": \"1.13kg\",\n    \"Processor\": \"Intel Core i7\",\n    \"Clock speed\": \"2.6GHz\",\n    \"Budget\": \"130000\"\n}", "{\n    \"Category\": \"general\",\n    \"Brand\": \"Acer\",\n    \"Model Name\": \"Swift 3\",\n    \"GPU processor\": \"Radeon\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"1.2kg\",\n    \"Processor\": \"Ryzen\",\n    \"Clock speed\": \"2.3GHz\",\n    \"Budget\": \"50000\"\n}", "{\n    \"Category\": \"general\",\n    \"Brand\": \"Apple\",\n    \"Model Name\": \"MacBook Air\",\n    \"GPU processor\": \"M1\",\n    \"Display Resolution\": \"2560x1600\",\n    \"Weight\": \"1.29kg\",\n    \"Processor\": \"Apple M1\",\n    \"Clock speed\": \"3.2GHz\",\n    \"Budget\": \"100000\"\n}", "{\n    \"Category\": \"business\",\n    \"Brand\": \"MSI\",\n    \"Model Name\": \"Prestige 14\",\n    \"GPU processor\": \"NVIDIA\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"1.29kg\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.4GHz\",\n    \"Budget\": \"70000\"\n}", "{\n    \"Category\": \"business\",\n    \"Brand\": \"ASUS\",\n    \"Model Name\": \"ZenBook 13\",\n    \"GPU processor\": \"Intel Iris Xe\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"1.11kg\",\n    \"Processor\": \"Intel Core i7\",\n    \"Clock speed\": \"2.8GHz\",\n    \"Budget\": \"95000\"\n}", "{\n    \"Category\": \"business\",\n    \"Brand\": \"Dell\",\n    \"Model Name\": \"Precision 5550\",\n    \"GPU processor\": \"NVIDIA Quadro\",\n    \"Display Resolution\": \"3840x2160\",\n    \"Weight\": \"1.83kg\",\n    \"Processor\": \"Intel Xeon\",\n    \"Clock speed\": \"2.6GHz\",\n    \"Budget\": \"250000\"\n}", "{\n    \"Category\": \"general\",\n    \"Brand\": \"HP\",\n    \"Model Name\": \"ENVY x360\",\n    \"GPU processor\": \"Intel Iris Xe\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"2.05 kg\",\n    \"Processor\": \"Intel Core i7\",\n    \"Clock speed\": \"2.8 GHz\",\n    \"Budget\": \"80000\"\n}", "{\n    \"Category\": \"gamer\",\n    \"Brand\": \"Razer\",\n    \"Model Name\": \"Blade 15\",\n    \"GPU processor\": \"NVIDIA RTX\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"2.09kg\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.6GHz\",\n    \"Budget\": \"150000\"\n}", "{\n    \"Category\": \"business\",\n    \"Brand\": \"Apple\",\n    \"Model Name\": \"MacBook Pro\",\n    \"GPU processor\": \"AMD\",\n    \"Display Resolution\": \"3072x1920\",\n    \"Weight\": \"2.02 kg\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.9 GHz\",\n    \"Budget\": \"280000\"\n}"]

In [82]:
print(type(json_data[0]))

<class 'str'>

In [65]:
import pandas as pd
try:
  df_data = pd.DataFrame(json_data)
  print(df_data)
except Exception as e:
  print(f"An error occurred: {e}")

An error occurred: DataFrame constructor not properly called!

In [66]:
import json
import re

In [67]:
# Function to remove special characters
def remove_special_characters(value):
    # Define pattern for special characters
    pattern = r'[\n\\]'
    # Remove special characters
    return re.sub(pattern, '', value)

In [73]:
data1 = input_string.replace("\\n", "").replace("\\", "").replace("  ", "").replace("\n", "")

In [74]:
data1

'{"Category": "general","Brand": "Dell","Model Name": "Inspiron","GPU processor": "Intel","Display Resolution": "1920x1080","Weight": "2.5kg","Processor": "Intel","Clock speed": "2.4GHz","Budget": "35000"}'

In [76]:
# Clean dictionary values
data = {"Category": "general","Brand": "Dell","Model Name": "Inspiron","GPU processor": "Intel","Display Resolution": "1920x1080","Weight": "2.5kg","Processor": "Intel","Clock speed": "2.4GHz","Budget": "35000"}
cleaned_data = {key: remove_special_characters(value) for key, value in data.items()}

In [77]:
cleaned_data

{'Category': 'general',
 'Brand': 'Dell',
 'Model Name': 'Inspiron',
 'GPU processor': 'Intel',
 'Display Resolution': '1920x1080',
 'Weight': '2.5kg',
 'Processor': 'Intel',
 'Clock speed': '2.4GHz',
 'Budget': '35000'}

In [ ]:
input_string = '"{\n    \"Category\": \"general\",\n    \"Brand\": \"Dell\",\n    \"Model Name\": \"Inspiron\",\n    \"GPU processor\": \"Intel\",\n    \"Display Resolution\": \"1920x1080\",\n    \"Weight\": \"2.5kg\",\n    \"Processor\": \"Intel\",\n    \"Clock speed\": \"2.4GHz\",\n    \"Budget\": \"35000\"\n}"'

In [68]:
input_string = """{
    \"Category\": \"general\",
    \"Brand\": \"Dell\",
    \"Model Name\": \"Inspiron\",
    \"GPU processor\": \"Intel\",
    \"Display Resolution\": \"1920x1080\",
    \"Weight\": \"2.5kg\",
    \"Processor\": \"Intel\",
    \"Clock speed\": \"2.4GHz\",
    \"Budget\": \"35000\"
}"""

In [71]:
cleaned_string = input_string.replace("\\n", "").replace("\\", "").replace("  ", "").replace("\n", "")

In [72]:
cleaned_string

'{"Category": "general","Brand": "Dell","Model Name": "Inspiron","GPU processor": "Intel","Display Resolution": "1920x1080","Weight": "2.5kg","Processor": "Intel","Clock speed": "2.4GHz","Budget": "35000"}'